language: ruby
bundler_args: --without debug
rvm:
  - ruby-head
  - jruby-head
  - jruby-19mode
  - rbx-19mode
  - rbx-2
  - 1.9.3
  - 2.0.0
  - 2.1.0
script:
  - bundle exec rspec
  - bundle exec rubocop
