language: ruby
rvm:
  - ruby-head
  - jruby-head
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
  - rbx-2
  - ree
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
bundler_args: --without development
